EcommerceApp/Controllers/ClientController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using EcommerceApp.Models;
using Microsoft.AspNet.Identity;

namespace EcommerceApp.Controllers
{
    public class ClientController : Controller
    {
        DataClasses1DataContext dc = new DataClasses1DataContext();

        // GET: Client
        public ActionResult Index()
        {
            var data = dc.Products.ToList();
            return View(data);
        }
        [HttpPost]
        [Authorize]
        public ActionResult AddtoCart(Product z)
        {
            try
            {

                var username = User.Identity.GetUserName();
                string str = Request["quantity"];
                int quantity = 1;
                Cart obj = new Cart();

                var data = dc.Carts.Where(x => x.Id == z.Id).FirstOrDefault();

                obj.ProductId = z.Id;
                obj.UserName = username;

                obj.Quantity = quantity;
                obj.orderDate = DateTime.Today;
                dc.Carts.InsertOnSubmit(obj);
                dc.SubmitChanges();
            }
            catch (Exception e)
            {
                
            }
          

            return RedirectToAction("Index");
           
        }

        public ActionResult Delete()
        {
            var username = User.Identity.GetUserName();
            var c = dc.Carts.Where(x => x.UserName==username).ToList();
            return View(c);
        }
        public ActionResult DeleteCart(int id)
        {
            var s = dc.Carts.First(x => x.Id == id);
            dc.Carts.DeleteOnSubmit(s);
            dc.SubmitChanges();
            return RedirectToAction("Delete");
        }

        public ActionResult CheckOut()
        {
            var username = User.Identity.GetUserName();
            var c = dc.Carts.Where(x => x.UserName == username).ToList();
           
            return View(c);
        }

        public ActionResult Sales()
        {
            var str = from a in dc.Carts where a.UserName==User.Identity.GetUserName() select a;
            foreach (var val in str) // iterator the data from the list and insert them into the listSecond
            {
                Sale ls = new Sale {Sales_person_name = val.UserName, Amount = Convert.ToInt32(val.Product.Price),Status = "Pending",Unit = val.Product.Unit,Category = val.Product.Category,gst = 16.3 ,Discount = 5,Date = DateTime.Today};
                dc.Sales.InsertOnSubmit(ls);
                dc.Carts.DeleteOnSubmit(val);  
                dc.SubmitChanges();
            }
            return View("AddtoCart");
        }
        public ActionResult MyOrders()
        {
            var Orders = dc.Sales.Where(x => x.Sales_person_name == User.Identity.GetUserName()).ToList();
            return View(Orders);
        }


    }
}

EcommerceApp/Controllers/TestController.cs
using System.Web.Mvc;

namespace EcommerceApp.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult NavigationController()
        {
            return PartialView("_sidebar");
        }
       
    }
}

EcommerceApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - EcommerceApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    



</head>
<body id="main">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container container-fluid">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ecommerce Application", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@

                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div>

        @{
            Html.RenderAction("NavigationController", "Test");
        }
        @*@if (Request.IsAuthenticated)
            {

                {


                }
            }*@
    </div>
    @{
        string action = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("action");

        string Controller = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("controller");

    }
    <div class="breadcrumb container">
        <h3>
            @Controller/@action
        </h3>
    </div>
    <div class="container">

        @RenderBody()

        <hr />
        <footer>
            <p>© 2019 -ABC Technologies </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/admin-lte/js")
    @RenderSection("scripts", required: false)
    @RenderSection("stripe", required: false)
</body>
</html>

EcommerceApp/Views/Shared/_sidebar.cshtml
@using Microsoft.AspNet.Identity;
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">



    <link href="~/css/adminstyle.css" rel="stylesheet" />

</head>
<body onload="myFunction()">
<style>
    
    </style>
<div id="mySidenav" class="sidenav">
   

    <img src="~/Images/E-Commerce-Summit-LOGO.png" alt="ecom_logo" height="60" width="180" style="margin-left: 15px"/>
    <a href="javascript:void(0)" id="cross" class="closebtn" onclick="closeNav()">&times;</a>
    @if (User.IsInRole("Admin"))
    {
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="navbar-nav" style="margin-left: -40px">
                <li class="dropdown" >
                    <a id="cli" href="#" style="margin-left:-16px">Admin Panel<span class="caret admin"></span></a>
                    <ul id="show" style="display: block; list-style-type: none; margin-left:-55px;">
                        <li><a href="/Admin/Index"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                        <li><a href="/Admin/Adminlte"><span class="glyphicon glyphicon-user"></span> Add User</a></li>
                        <li><a href="/Admin/Units"><span class="glyphicon glyphicon-cloud"></span> Create Units</a></li>
                        <li><a href="/Admin/Product"><span class="glyphicon glyphicon-apple"></span> Create Products</a></li>
                        <li><a href="/Admin/Category"><span class="glyphicon glyphicon-barcode"></span> Create Categories</a></li>
                    </ul>
                </li>
            </ul>
        </div>

        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class=" navbar-nav" style="margin-left: -40px">
                <li class="dropdown">
                    <a id="reports" href="#" style="margin-left:-16px">Reports<span class="caret admin"></span></a>
                    <ul id="showreports" style="display: block; list-style-type: none; margin-left:-55px;">
                        <li><a href="/Admin/ProductWise"><span class="glyphicon glyphicon-apple"></span> Product Wise</a></li>
                        <li><a href="/Admin/AllSales"><span class="glyphicon glyphicon-calendar"></span> Date Wise</a></li>
                        <li><a href="/Admin/AllSales"><span class="glyphicon glyphicon-sort-by-order"></span> All Order History</a></li>
                        <li><a href="/Admin/AllSales"><span class="glyphicon glyphicon-sort-by-attributes"></span> All Transection History</a></li>
                        <li><a href=""><span class="glyphicon glyphicon-sort-by-alphabet" ></span> Ledger</a></li>
                        <li><a href=""><span class="glyphicon glyphicon-sort-by-order-alt"></span> Party Ledger Also</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    }
    <br/>
    @if (User.IsInRole("User"))
    {
        <li>@Html.ActionLink("MyOrders", "MyOrders", "Client")</li>
    }
    @if (User.IsInRole("Admin"))
    {
        <a href="/Admin/AllSales"><span class="glyphicon glyphicon-credit-card"></span> Sales</a>
    }
    @if (!(User.IsInRole("Admin")))
    {
        <a href="/Client/CheckOut"><span class="glyphicon glyphicon-credit-card"></span> Check Out</a>
        <a href="/Client/Delete"><span class="glyphicon glyphicon-shopping-cart"></span> Check Your Cart</a>
    }
     <a href="/Client/MyOrders"><span class="glyphicon glyphicon-apple"></span> My Orders</a>
    <a href="/Home/About"><span class="glyphicon glyphicon-info-sign"></span> About</a>
    <a href="/Home/Contact"><span class="glyphicon glyphicon-phone"></span>Contact</a>
</div>

<div id="main">
    <br/>
    <span style="font-size:20px; cursor: pointer;display:none" id="menu"   onclick="opennav()">&#9776; MENU</span>
</div>

<script>
    function myFunction() {
        document.getElementById("mySidenav").style.width = "250px";
        document.getElementById("main").style.marginLeft = "250px";
    }
        
    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
        document.getElementById("main").style.marginLeft = "0";
        $('#cross').css("display", "none");
        $('#menu').css("display", "block");
    }
    function opennav() {
        document.getElementById("mySidenav").style.width = "250px";
        document.getElementById("main").style.marginLeft = "250px";
        $('#menu').css("display","none");
        $('#cross').css("display", "block");
    }

    $(document).ready(function() {
        $("#cli").click(function () {
            $("#show").toggle("slow");
        });
    });

    $(document).ready(function () {
        $("#reports").click(function () {
            $("#showreports").toggle("slow");
        });
    });
    $("#menu").on('click', function() {
       
    });
    $("#cross").on('click', function () {

    });
</script>



</body>